export const productImages = [
  { name: 'Lamp', src: '/lamp.jpg', id: 19 },
  { name: 'chicChair', src: '/chair.jpg', id: 12 },
  { name: 'coffeeTable', src: '/coffee_table.jpg', id: 6 },
  { name: 'Bed', src: '/bed.jpg', id: 7 },
  { name: 'contemporarySofa', src: '/hero1.webp', id: 13 },
  { name: 'cuttingEdgeBed', src: '/hero4.webp', id: 20 },
  { name: 'futuristicShelves', src: '/shelves.jpg', id: 16 },
  { name: 'glassTable', src: '/hero2.webp', id: 21 },
  { name: 'kingBed', src: '/kingBed.jpg', id: 22 },
  { name: 'loungeChair', src: '/loungeChair.jpg', id: 24 },
  { name: 'sleek_chair', src: '/sleek_chair.jpg', id: 4 },
  { name: 'sleek_bed', src: '/sleek_bed.jpg', id: 10 },
  { name: 'stylish_bed', src: '/stylish_bed.jpg', id: 15 },
  { name: 'modern_table', src: '/modern_table.jpg', id: 9 },
  { name: 'streamlined_table', src: '/streamlined_table.jpg', id: 14 },
];
