export const productImages = [
  { name: 'Lamp', src: 'store/lamp.jpg', id: 19 },
  { name: 'chicChair', src: 'store/chair.jpg', id: 12 },
  { name: 'coffeeTable', src: 'store/coffee_table.jpg', id: 6 },
  { name: 'Bed', src: 'store/bed.jpg', id: 7 },
  { name: 'contemporarySofa', src: 'store/hero1.webp', id: 13 },
  { name: 'cuttingEdgeBed', src: 'store/hero4.webp', id: 20 },
  { name: 'futuristicShelves', src: 'store/shelves.jpg', id: 16 },
  { name: 'glassTable', src: 'store/hero2.webp', id: 21 },
  { name: 'kingBed', src: 'store/kingBed.jpg', id: 22 },
  { name: 'loungeChair', src: 'store/loungeChair.jpg', id: 24 },
  { name: 'sleek_chair', src: 'store/sleek_chair.jpg', id: 4 },
  { name: 'sleek_bed', src: 'store/sleek_bed.jpg', id: 10 },
  { name: 'stylish_bed', src: 'store/stylish_bed.jpg', id: 15 },
  { name: 'modern_table', src: 'store/modern_table.jpg', id: 9 },
  { name: 'streamlined_table', src: 'store/streamlined_table.jpg', id: 14 },
  { name: 'sectional_sofa', src: 'store/sectional_sofa.jpg', id: 25 },
  { name: 'velvet_sofa', src: 'store/velvet_sofa.jpg', id: 17 },
  { name: 'minimalist_shelves ', src: 'store/minimalist_shelves.jpg', id: 11 },
  { name: 'modern_sofa', src: 'store/modern_sofa.jpg', id: 5 },
  { name: 'reclining_sofa', src: 'store/reclining_sofa.jpg', id: 18 },
  { name: 'toy_shelf', src: 'store/toy_shelf.jpg', id: 23 },
  { name: 'wooden_shelves', src: 'store/wooden_shelves.jpg', id: 8 },
];
